# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://oliveradk.github.io/lifelong_disrep/"

git_url = "https://github.com/oliveradk/lifelong_disrep/tree/master/"

def custom_doc_links(name): return None
