# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"PARENT_DIR": "00b_config.ipynb",
         "DATA_PATH": "00b_config.ipynb",
         "PARAM_PATH": "00b_config.ipynb",
         "rec_likelihood": "00c_core.utils.ipynb",
         "kl_div_stdnorm": "00c_core.utils.ipynb",
         "CommonMNIST": "01a_core.datasets.moving_mnist.ipynb",
         "CommonFashionMNIST": "01a_core.datasets.moving_mnist.ipynb",
         "MovingMNIST": "01a_core.datasets.moving_mnist.ipynb",
         "MovingFashionMNIST": "01a_core.datasets.moving_mnist.ipynb",
         "FixedMNIST": "01a_core.datasets.moving_mnist.ipynb",
         "Encoder": "02a_core.models.ipynb",
         "FCEncoder": "02a_core.models.ipynb",
         "EnvironmentInference": "02a_core.models.ipynb",
         "env_dist_to_one_hot": "02a_core.models.ipynb",
         "Decoder": "02a_core.models.ipynb",
         "FCDecoder": "02a_core.models.ipynb",
         "reparam": "02a_core.models.ipynb",
         "VanillaVAE": "02a_core.models.ipynb",
         "PaperVanillaVAE": "02a_core.models.ipynb",
         "FCVAE": "02a_core.models.ipynb",
         "latent_mask": "02a_core.models.ipynb",
         "apply_mask": "02a_core.models.ipynb",
         "LatentMaskVAE": "02a_core.models.ipynb",
         "EnvInferVAE": "02a_core.models.ipynb",
         "reconstruction_loss": "03a_core.train.ipynb",
         "kl_div_target": "03a_core.train.ipynb",
         "euclidean": "00c_core.utils.ipynb",
         "encoder_proximity": "03a_core.train.ipynb",
         "decoder_proximity": "03a_core.train.ipynb",
         "env_dist_to_idx": "02a_core.models.ipynb",
         "generate_samples": "02a_core.models.ipynb",
         "GenReplayVAE": "02a_core.models.ipynb",
         "show": "00c_core.utils.ipynb",
         "show_batch": "00c_core.utils.ipynb",
         "disable_gradient": "00c_core.utils.ipynb",
         "enable_gradient": "00c_core.utils.ipynb",
         "EnvInferGAVAE": "02a_core.models.ipynb",
         "LOG_PATH": "00b_config.ipynb",
         "VASE": "02b_core.vase_model.ipynb",
         "CLVAE": "02c_core.clvae.ipynb"}

modules = ["config.py",
           "core/utils.py",
           "core/datasets/moving_mnist.py",
           "core/models.py",
           "core/train.py",
           "core/vase_model.py",
           "core/clvae.py"]

doc_url = "https://oliveradk.github.io/vase/"

git_url = "https://github.com/oliveradk/vase/tree/master/"

def custom_doc_links(name): return None
