# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"PARENT_DIR": "00b_config.ipynb",
         "DATA_PATH": "00b_config.ipynb"}

modules = ["config.py"]

doc_url = "https://oliveradk.github.io/vase/"

git_url = "https://github.com/oliveradk/vase/tree/master/"

def custom_doc_links(name): return None
