# AUTOGENERATED! DO NOT EDIT! File to edit: 00b_config.ipynb (unless otherwise specified).

__all__ = ['PARENT_DIR', 'DATA_PATH', 'PARAM_PATH']

# Cell
import os
import vase

# Cell
PARENT_DIR = os.path.dirname(vase.__file__)

# Cell
DATA_PATH = os.path.join(PARENT_DIR, 'data')

# Cell
PARAM_PATH = os.path.join(PARENT_DIR, 'params')