# AUTOGENERATED! DO NOT EDIT! File to edit: 00a_config.ipynb (unless otherwise specified).

__all__ = ['PARENT_DIR', 'DATA_PATH', 'PARAM_PATH', 'LOG_PATH']

# Cell
import os
import cult

# Cell
PARENT_DIR = os.path.dirname(cult.__file__)

# Cell
DATA_PATH = os.path.join(PARENT_DIR, 'data')

# Cell
PARAM_PATH = os.path.join(PARENT_DIR, 'params')

# Cell
LOG_PATH = os.path.join(PARENT_DIR, 'logs')